# Generated by Django 4.2.11 on 2024-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_level_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='subLevel',
            field=models.IntegerField(default=1),
        ),
    ]
